apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5lkx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-5lkx@sha256:5aac719840b03f64e3cf16955bc00641ecf6e7c5c283fd88ea561dab4617e366
        name: my-nodejs
        resources: {}
status: {}
